### ISSUE TITLE
Fail to Import External Module 

### ISSUE THREAD

**Issue by selfeduedu** [saml-dev/obsidian-custom-js#48]
Hi there,

I'm currently facing an issue with importing an external module in my JavaScript code. I was able to successfully import and use the module for the past few days, but today it suddenly stopped working. I have tried restarting Vault and reinstalling the Custom JS, but it hasn't resolved the problem.

Here's the import statement I'm using: 
![image](https://github.com/saml-dev/obsidian-custom-js/assets/84117733/424495e7-8d33-4a2e-8fa8-4dbab349fb26)

My file is test.js, and I am trying to import pinyin-pro. I have verified that the module is installed and accessible in my environment. However, when I try to import it, I receive an error.
![image](https://github.com/saml-dev/obsidian-custom-js/assets/84117733/7a5ef68d-68e2-4dcd-a418-f4c4535b58dd).

I would greatly appreciate any assistance or guidance on how to troubleshoot and resolve this issue. Please let me know if you need any additional information.

Thank you!

**Comment by saml-dev** [comment]
I would stay away from `app.vault.adapter.basePath` as it doesn't work on mobile. If you don't care about mobile then it may be fine to use, not sure. Use at your own risk.

Notice the errors say `CustomJS couldn't import js/scripts/pinyin-pro/dist/index.es.js`. So `this.basepath` is empty. Again, I'd recommend staying away from it. 

CustomJS uses `app.vault.getFiles()` to retrieve files. Maybe you can find a work around. But the reason CustomJS is so finnicky is because `require` and `import` statements generally aren't possible due to Obsidian limitations. So I can't help beyond this comment, sorry.
https://github.com/saml-dev/obsidian-custom-js/blob/a80f85aa6563e62b08c4e8dc474e4d6dc1f8e1ec/main.ts#L92

**Comment by a13ph** [comment]
I assume that if someone wants to use external modules, then the best way around this currently is to build a plugin which imports those modules and to someho exposes in it functions constructed that way for reuse in dataviewjs
