### ISSUE TITLE
Want to reformat notes

### ISSUE THREAD

**Issue by dvansoye** [saml-dev/obsidian-custom-js#69]
Hi,
I'm looking for a way to reformat the notes that I import into Obsidian. I want to capitalize the first letter of each line and add a period to the end if there isn't one there already. I have a python program that I run in Colab that works. But, I have to copy and paste the data. It would be far better if I could perform the reformatting operation directly inside of Obsidian. 

I was wondering if I could convert my python program to JavaScript and run it after opening a note that I wanted to reformat. Is Custom-js a good choice for this? Can it operate on the entire note and reformat it.

Looking for your recommendation on how to best implement this. 

Thanks,
Darren

**Comment by saml-dev** [comment]
It might be possible, but I highly recommend you just use your script on your markdown files directly rather trying to do this within Obsidian itself. Instead of copying and pasting, just point your script to your markdown file on your local file system. That's one of the benefits of Obsidian is it's just a view for your markdown files.
