### ISSUE TITLE
How to import js into script?

### ISSUE THREAD

**Issue by ShahriarKh** [saml-dev/obsidian-custom-js#84]
How can I import another js script and use it?

For example:
```js
import * as externalScript from './external.js'

class MyClass {
  myFunc() {
    externalScript.someFunction()
  }
}
```
I tried something like this, but am not sure if it's the best way:
```js
class CoolString {
  constructor() {
    var scriptElement = document.createElement("script");
    scriptElement.src = app.vault.adapter.getResourcePath("scripts/functionplot.js");
    document.head.appendChild(scriptElement);
  }

  plot(settings) {
    functionPlot(settings);
  }
}
```

**Comment by tj-21-biggs** [comment]
Imports do not work within these scripts because of the way they are loaded. Every script is loaded on startup and a singleton is created. You can read more here. #77 

Basically, if you want to use the singleton: `const { ClassName } = customJS;`

And if you want to create a new instance: `const ClassName = customJS.createClassNameInstance();`

It does appear that it is impossible to reference a static function from another class though.

**Comment by saml-dev** [comment]
thanks @tj-21-biggs
